# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  S3_BUCKET_NAME: dawheen-build

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name : Setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install
      working-directory: sos_front

    - name: Build Vue application
      run: npm run build
      working-directory: sos_front

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - run: gradle init
    
    - name: Build with Gradle Wrapper
      run: ./gradlew build

    # 파일 압축
    - name: Make zip file
      run: zip -r ./sos.zip .
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }} # 등록한 Github Secret이 자동으로 불려온다.
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # 등록한 Github Secret이 자동으로 불려온다.
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./sos.zip s3://$S3_BUCKET_NAME/sos.zip
      # 압축된 파일 지정

    - name: Code Deploy
      run: >
        aws deploy create-deployment --application-name dawheen
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name dawheen-group
        --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=sos.zip

